timings:
  scout_wait: 6.0
  attack_duration: 40
  reconnect_wait: 10
  match_wait: 8
  troop_engage_wait: 10
  hero_ability_activate_after_deployment: 20
  result_screen_wait: 14

regions:
  loot_region:
    (122, 240, 93, 99)
  wifi_icon:

camera:
  start: [802, 529]
  end: [106, 862]

deploy:
  troops:
    - name: dragons
      type: drag
      slot: [309, 911]
      drag_start: [851, 251]
      drag_end: [277, 636]
      duration: 1.5

    - name: siege
      type: click
      slot: [412, 905]
      target: [567, 424]

  heroes:
    - name: hero_1
      slot: [509, 900]
      target: [567, 420]

    - name: hero_2
      slot: [600, 900]
      target: [567, 420]

    - name: hero_3
      slot: [701, 906]
      target: [567, 420]

    - name: hero_4
      slot: [786, 906]
      target: [567, 420]

  spells:
    - name: bat_spell
      slot: [893, 906]
      target: [567, 420]
      count: 11

  hero_abilities:
    - [509, 900]
    - [600, 900]
    - [701, 900]
    - [786, 906]

thresholds:
  8:
    gold_elixir_total: 200000
    dark_elixir: 1000

  9:
    gold_elixir_total: 500000
    dark_elixir: 1200

  10:
    gold_elixir_total: 600000
    dark_elixir: 2000

  11:
    gold_elixir_total: 800000
    dark_elixir: 3000

  12:
    gold_elixir_total: 1100000
    dark_elixir: 5000

  13:
    gold_elixir_total: 1400000
    dark_elixir: 6000

  14:
    gold_elixir_total: 1600000
    dark_elixir: 7000

  15:
    gold_elixir_total: 1700000
    dark_elixir: 8000

  16:
    gold_elixir_total: 1850000
    dark_elixir: 9000

  17:
    gold_elixir_total: 2000000
    dark_elixir: 10000

  18:
    gold_elixir_total: 240000
    dark_elixir: 10000
